dist: trusty
sudo: false

language: node_js
node_js:
  - '8'

cache:
  yarn: true
  directories:
  - node_modules


install:
  - yarn install

script:
  - yarn lint
  - env

after_success:
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then curl ${JENKINS_DEPLOY_URL}; fi'

