dist: trusty
sudo: required

language: node_js
node_js:
  - '8'

addons:
  chrome: stable

cache:
  yarn: true
  directories:
  - node_modules

before_install:
  - google-chrome-stable --headless --no-sandbox

install:
  - yarn install

script:
  - xvfb-run -a yarn test --watch=false --progress=false --browser=ChromeHeadlessCI
  - xvfb-run -a yarn e2e
