dist: trusty
sudo: required

language: node_js
node_js:
  - '8'

addons:
  chrome: stable

cache:
  yarn: true
  directories:
  - node_modules

install:
  - yarn install

script:
  - yarn test --watch=false --progress=false --browsers=ChromeHeadlessCI --code-coverage
  - yarn e2e

after_script:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
